on:
  workflow_dispatch:
    inputs:
      version:
        description: Version Overwrite
        required: false
  push:
    tags:
      - "v*"
name: GoReleaser

env:
  VERSION: ${{ github.event.inputs.version || (startsWith(github.ref, 'refs/tags/') && github.ref || '') }}

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Install Deps
        run: |
          sudo apt install -y make
          go get -u golang.org/x/lint/golint
          go get -u github.com/jteeuwen/go-bindata/go-bindata
      - uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
